version: 2.1
orbs:
  qlty-orb: qltysh/qlty-orb@0.0
jobs:
  build:
    docker:
      - image: cimg/node:lts

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: sudo npm link serviceberry

      - run:
          name: Run tests
          command: npm run build

      - qlty-orb/coverage_publish:
          files: coverage

  deploy-website:
    docker:
      - image: cimg/node:lts

    steps:
      - checkout
      - run:
          name: Deploying to GitHub Pages
          command: |
            git config --global user.email "gray.bob98@gmail.com"
            git config --global user.name "Bob Gray"
            echo "machine github.com login bob-gray password $GITHUB_TOKEN" > ~/.netrc
            cd website && npm install && GIT_USER=bob-gray npm run publish-gh-pages

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy-website
