version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.10

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: npm install

      - run: npm install eslint -g

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm test

  deploy-website:
    docker:
      - image: circleci/node:8.10

    steps:
      - checkout
      - run:
          name: Deploying to GitHub Pages
          command: |
            git config --global user.email "gray.bob98@gmail.com"
            git config --global user.name "Bob Gray"
            echo "machine github.com login bob-gray password $GITHUB_TOKEN" > ~/.netrc
            cd website && npm install && GIT_USER=bob-gray npm run publish-gh-pages

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy-website
